### ISSUE TITLE
ขอคำชี้แนะทีครับ

### ISSUE THREAD

**Issue by 1ikethat** [pkpgdjk/HappyHogBotV2#2]
อยากทราบวิธีแกะ api ใช้กระบวนท่าไหนหรอครับ รบกวนผู้อาวุโสโปรดชี้แนะด้วยครับ ☺

**Comment by pkpgdjk** [comment]
ios ใช้ app proxyman ในเครื่องได้เลยครับ 
android น่าจะต้อง root แล้ว ติดตั้ง root cert ก่อนครับ

**Comment by 1ikethat** [comment]
> app proxyman

ขอบคุณมากๆครับ
